[project]
name = "ncells_from_cells"
version = "0.0.1"
dependencies = [
    "numpy",
    "pyvista"
]

[build-system]
requires = ["numpy", "cython", "setuptools", "wheel"]
build-backend = "setuptools.build_meta"